# Generated by Django 3.2.5 on 2021-07-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='First Name', max_length=50)),
                ('last_name', models.CharField(default='Last Name', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=16)),
                ('email', models.EmailField(default='', max_length=255)),
                ('notes', models.TextField(default='etc...')),
            ],
        ),
    ]
